version: "3.9"

services:
  app:
    build: .
    container_name: clincore_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:


  db:
    image: postgres:16-alpine
    container_name: clincore_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: clincore
      POSTGRES_USER: clincore_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clincore_user -d clincore"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
